### ISSUE TITLE
Rotation-Test using v2.0.0 Demo

### ISSUE THREAD

**Issue by edgar79** [nicarran/jpen#5]
Hello,

I tested the rotation-values of a Wacom Art Pen as mentioned in the PLevel javadoc:

- On macOS 10.12 rotation is not working. The value stays at 0.0°. (I didn't look at the code yet.)

On Windows 10 and Debian Jessie (stable) rotation is working and a complete rotation of the pen results in 360°, but:

- On Windows 10 the value increases counter clockwise

- On Linux the value increases clockwise.

And the pen position at 0° is different on Linux and Windows:

- On Windows 10:  when the pen is held at a value of 0° rotation the buttons point at 09 o'clock, resulting in buttons being \~ upside when the pen is held in the right hand. 

- On Linux the buttons point at 45° between 03 and 06 o'clock when the pen is held at a rotation value of 0°. The buttons point \~ downside if it is held in the right hand.

**Comment by edgar79** [comment]
Hello,

I tried to fix the rotation on macOS but I do not find the cause.

The NSEvent - directly in the native code - gives itself 0.0 rotation.

The code reads fine and I checked the mac os documentation 
and the sample code from developer.wacom.com 
and everything seems to be ok (considering rotation).

I ended up searching for a newer driver version and found
that the latest driver still supports this older model but the 
rotation stayed at 0.0 ...

One small irritation started reading Wacom's Mac Developer Guide as it
only uses Carbon events. But the used NSEvents are used
in the sample code in the same way, so I think it should work as it is (?)
( I thought it could also be an Art Pen/Intuos4/driver version/os version specific bug,
but i didn't find any hints using google)

I was searching if there is another way (or event type) to select the events
eventually containing the rotation data but I found that the code does it correctly.

---
Ah, and with the position of the buttons at 0° : this is not important.
Reading the documentation I realized that it's possible to change the button position
without "rotating" by moving the tilted pen around. (I have not tested this yet.)

---
EDITS: Trying to find a more polite translation

**Comment by edgar79** [comment]
Hello,

I tested the rotation in another mac OS application (Corel Painter Essential) 
and the rotation works there. So the bug is not on the driver side.
I will try to find the cause again.

**Comment by edgar79** [comment]
I tested the trick mentioned in the Mac API documentation, to move the tilted pen without rotating it to change the button position on the pen axis  and it didn't work as expected (on Windows 10 and Linux). Moving the tilted pen around without rotating it along it's axis is projected as rotation, so it always returns to 0° without changing the button position.

And the position of the buttons is constant over reboots etc. So it seems to be an constant offset
between Linuxwacom and Wintab, which could be handled by JPen or by the application using JPen.
But I don't know if it is just an offset between Linux and Windows or if it additionally depends
on the used devices... If it is a constant value, it could be easily fixed in JPen so that clients using the library can expect the same orientation on all providers. 

But if it is variable it could just be mentioned in the javadoc. As applications using rotation could
implement a configurable offset for rotation (also to be able to set the button position relatively too).

**Comment by edgar79** [comment]
Yesterday I tested with an older sample code project (using the same API) directly and rotation was constantly 0° there too. So I contacted developer.wacom.com and described my tests and configuration. May be they could point me to the right direction.

**Comment by nicarran** [comment]
Trying with the wacom driver 6.3.15-3 is probably worthwhile. [This post](http://forum.wacom.eu/viewtopic.php?f=6&t=28) about 6.3.19-6 by a wacom rep. is interesting:
>The driver was released because we have new products (Cintiq Pro) on the market. - There are a number of known issues, since not everything could be fixed in time. Since Apple changed pen and mouse/touch handling in the os with the release of Sierra, the tablet driver had to adjusted for that. But also applications should be modified accordingly. At the moment we see some programs using the new system, some use the older method and the tablet drivers tries to work for both cases (and also for older versions of PS and older versions of OSX). We need more time for that. If your tablet is supported with the 6.3.15 driver, it may work better with that version, depending on which functions you are using.

**Comment by edgar79** [comment]
Hello Nicolas,
I had used the driver 6.3.15-3 some time ago and just checked if rotation is working with it but it doesn't. So i use 6.3.17-5 for now, where the fractional pixels are ok. 

But thank you for researching this. The mentioned "new system" is interesting me. I had the impression that the API or something might have changed but until now I didn't find it in the documentation. So I will try to find out more about that.

**Comment by edgar79** [comment]
I just searched for a while now and found nothing new. Especially not how applications should be modified. So I will wait for an answer from developer.wacom.com.

I checked the Apple SDK documentation again and found no changes of the API (for mouse or tablet events). I assume it will be a matter of waiting for the next drivers for macOS Sierra.

**Comment by edgar79** [comment]
Hello,
I tested again with driver version 6.3.31-4 using jpen v2.0.0 release and **it works!**
Some time ago I read a driver changelog with a note about inverted rotation direction but I don't remember which version it was and didn't find it again.

So here are my test results using **jpen v2.0.0 demo (not master):**

_MacOS High Sierra 10.13.6 - Driver 6.3.31-4_
- pressure: ok
- fractional pixels: ok
- tilt: ok (integers)
- airbrush wheel (side-pressure): ok (0..1)
- rotation: increasing counter clockwise

_Windows 10 - Driver 6.3.31-4_
- pressure: ok
- fractional pixels: ok
- tilt: ok
- airbrush wheel (side-pressure): ok (0..1)
- rotation: increasing counter clockwise (Not inverted - v2.0.0)

_Debian Stretch (stable)_
- pressure: ok
- fractional pixels: ok
- tilt: ok (integers)
- airbrush wheel: ok ( 0 .. 0.999 - v2.0.0)
- rotation: increasing clockwise

---
_XInput:_

Using xinput side_pressure and rotation are coupled (wheel)...
See jpen/src/main/java/jpen/provider/xinput/XinputDevice.java - getMultRangedValue

Using the airbrush the wheel value increases in the right direction
but rotation is additionally increasing from 0 to 359.

Using the art pen, the rotation value is increasing clockwise
and side-pressure is increasing from 0 to 1 (clockwise)

At first I thought to revert the commit which inverts the rotation direction of the wintab provider and to invert the xinput rotation direction instead ( to get a consistent direction )
but I do not know if it is so easy to distinguish generically between airbrush, artpen etc. based on names (like stated in XinputDevice getMultRangedValue)...

May be it's easier to invert the rotation direction on macOS ...
